import type { Document, ValidationIssue } from '../types/document';

const now = new Date().toISOString();

export const mockDocuments: Document[] = [
  {
    id: 'doc-validated-invoice',
    documentType: 'INVOICE',
    documentNumber: 'INV-1005',
    supplierName: 'Company 5',
    issueDate: '2026-04-28',
    dueDate: '2026-05-28',
    currency: 'EUR',
    subtotal: 355,
    taxRate: 17,
    tax: 60.35,
    total: 415.35,
    status: 'VALIDATED',
    rejectReason: null,
    rawText:
      'Invoice\nSupplier: Company 5\nNumber: INV-1005\nDate: 2026-04-28\nService A 5 x 71 = 355\nTax 17% = 60.35\nTotal 415.35',
    fileName: 'invoice_6.pdf',
    fileUrl: '#',
    createdAt: '2026-04-28T10:10:00.000Z',
    updatedAt: now,
    lineItems: [
      {
        id: 'line-1005-1',
        description: 'Service A',
        quantity: 5,
        unitPrice: 71,
        lineTotal: 355,
      },
    ],
    validationIssues: [],
  },
  {
    id: 'doc-total-mismatch',
    documentType: 'INVOICE',
    documentNumber: 'INV-1000',
    supplierName: 'Company 0',
    issueDate: '2026-04-28',
    dueDate: '2026-05-28',
    currency: 'BAM',
    subtotal: 645,
    taxRate: 20,
    tax: 129,
    total: 800,
    status: 'NEEDS_REVIEW',
    rejectReason: null,
    rawText:
      'Invoice\nSupplier: Company 0\nNumber: INV-1000\nDate: 2026-04-28\nService A 5 x 129 = 645\nTax 20% = 129\nTotal 800.0',
    fileName: 'invoice_1.pdf',
    fileUrl: '#',
    createdAt: '2026-04-28T10:02:00.000Z',
    updatedAt: now,
    lineItems: [
      {
        id: 'line-1000-1',
        description: 'Service A',
        quantity: 5,
        unitPrice: 129,
        lineTotal: 645,
      },
    ],
    validationIssues: [
      {
        id: 'issue-total-1000',
        field: 'total',
        message: 'Total mismatch. Expected 774.00, extracted 800.00.',
        severity: 'ERROR',
        resolved: false,
      },
    ],
  },
  {
    id: 'doc-txt-missing-fields',
    documentType: 'INVOICE',
    documentNumber: 'TXT-0',
    supplierName: null,
    issueDate: null,
    dueDate: null,
    currency: 'EUR',
    subtotal: null,
    taxRate: null,
    tax: null,
    total: 758,
    status: 'NEEDS_REVIEW',
    rejectReason: null,
    rawText: 'Invoice TXT-0\nTotal: 758 EUR',
    fileName: 'text_1.txt',
    fileUrl: '#',
    createdAt: '2026-04-28T10:05:00.000Z',
    updatedAt: now,
    lineItems: [],
    validationIssues: [
      missingIssue('supplierName', 'Supplier/company name is missing.'),
      missingIssue('issueDate', 'Issue date is missing.'),
      missingIssue('dueDate', 'Due date is missing.'),
      missingIssue('lineItems', 'No line items were extracted.'),
      missingIssue('subtotal', 'Subtotal is missing.'),
      missingIssue('tax', 'Tax amount is missing.'),
    ],
  },
  {
    id: 'doc-po-2000',
    documentType: 'PURCHASE_ORDER',
    documentNumber: 'PO-2000',
    supplierName: 'Buyer 0',
    issueDate: '2026-04-28',
    dueDate: '2026-05-28',
    currency: 'BAM',
    subtotal: 288,
    taxRate: 0,
    tax: 0,
    total: 288,
    status: 'VALIDATED',
    rejectReason: null,
    rawText:
      'Purchase Order\nSupplier: Buyer 0\nNumber: PO-2000\nDate: 2026-04-28\nItem X 3 x 96 = 288\nTax 0% = 0\nTotal 288',
    fileName: 'po_1.pdf',
    fileUrl: '#',
    createdAt: '2026-04-28T10:06:00.000Z',
    updatedAt: now,
    lineItems: [
      {
        id: 'line-po-2000-1',
        description: 'Item X',
        quantity: 3,
        unitPrice: 96,
        lineTotal: 288,
      },
    ],
    validationIssues: [],
  },
  {
    id: 'doc-po-2001',
    documentType: 'PURCHASE_ORDER',
    documentNumber: 'PO-2001',
    supplierName: 'Buyer 1',
    issueDate: '2026-04-28',
    dueDate: '2026-05-28',
    currency: 'BAM',
    subtotal: 165,
    taxRate: 0,
    tax: 0,
    total: 165,
    status: 'VALIDATED',
    rejectReason: null,
    rawText:
      'Purchase Order\nSupplier: Buyer 1\nNumber: PO-2001\nDate: 2026-04-28\nItem X 3 x 55 = 165\nTax 0% = 0\nTotal 165',
    fileName: 'po_2.pdf',
    fileUrl: '#',
    createdAt: '2026-04-28T10:07:00.000Z',
    updatedAt: now,
    lineItems: [
      {
        id: 'line-po-2001-1',
        description: 'Item X',
        quantity: 3,
        unitPrice: 55,
        lineTotal: 165,
      },
    ],
    validationIssues: [],
  },
  {
    id: 'doc-csv-line-items',
    documentType: 'UNKNOWN',
    documentNumber: null,
    supplierName: null,
    issueDate: null,
    dueDate: null,
    currency: null,
    subtotal: null,
    taxRate: null,
    tax: null,
    total: null,
    status: 'NEEDS_REVIEW',
    rejectReason: null,
    rawText: 'desc,qty,price,total\nItem,1,78,78\nItem,2,84,168',
    fileName: 'data_1.csv',
    fileUrl: '#',
    createdAt: '2026-04-28T10:08:00.000Z',
    updatedAt: now,
    lineItems: [
      { id: 'line-csv-1', description: 'Item', quantity: 1, unitPrice: 78, lineTotal: 78 },
      { id: 'line-csv-2', description: 'Item', quantity: 2, unitPrice: 84, lineTotal: 168 },
    ],
    validationIssues: [
      missingIssue('documentNumber', 'Document number is missing.'),
      missingIssue('supplierName', 'Supplier/company name is missing.'),
      missingIssue('issueDate', 'Issue date is missing.'),
      missingIssue('currency', 'Currency is missing.'),
      missingIssue('subtotal', 'Subtotal is missing.'),
      missingIssue('tax', 'Tax amount is missing.'),
      missingIssue('total', 'Total is missing.'),
    ],
  },
  {
    id: 'doc-image-ocr',
    documentType: 'INVOICE',
    documentNumber: '3205',
    supplierName: 'Supplier Img 5',
    issueDate: null,
    dueDate: null,
    currency: 'EUR',
    subtotal: null,
    taxRate: null,
    tax: null,
    total: 439,
    status: 'NEEDS_REVIEW',
    rejectReason: null,
    rawText: 'Invoice 3205\nSupplier Img 5\nTotal: 439 EUR',
    fileName: 'img_6.png',
    fileUrl: '#',
    createdAt: '2026-04-28T10:12:00.000Z',
    updatedAt: now,
    lineItems: [],
    validationIssues: [
      missingIssue('issueDate', 'Issue date is missing.'),
      missingIssue('dueDate', 'Due date is missing.'),
      missingIssue('lineItems', 'No line items were extracted.'),
      missingIssue('subtotal', 'Subtotal is missing.'),
      missingIssue('tax', 'Tax amount is missing.'),
    ],
  },
  {
    id: 'doc-unsupported-screenshot',
    documentType: 'UNKNOWN',
    documentNumber: null,
    supplierName: null,
    issueDate: null,
    dueDate: null,
    currency: null,
    subtotal: null,
    taxRate: null,
    tax: null,
    total: null,
    status: 'REJECTED',
    rejectReason: 'Unsupported document type',
    rawText: null,
    fileName: 'Screenshot 2026-04-28 at 16.10.54.png',
    fileUrl: '#',
    createdAt: '2026-04-28T10:20:00.000Z',
    updatedAt: now,
    lineItems: [],
    validationIssues: [
      {
        id: 'issue-unsupported',
        field: 'documentType',
        message: 'Unsupported document type.',
        severity: 'ERROR',
        resolved: false,
      },
    ],
  },
];

function missingIssue(field: string, message: string): ValidationIssue {
  return {
    id: `issue-${field}-${Math.random().toString(16).slice(2)}`,
    field,
    message,
    severity: 'WARNING',
    resolved: false,
  };
}
